import { NavBar } from '@/components/nav-bar'
import type { Metadata } from 'next'
import { Baloo_2, Roboto } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '700'],
})

const baloo2 = Baloo_2({
  variable: '--font-baloo-2',
  subsets: ['latin'],
  weight: ['700', '800'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${baloo2.variable} antialiased`}
    >
      <body className="bg-background text-base-text *:select-none">
        <NavBar />
        <main>{children}</main>
        <Toaster richColors />
        <footer className="h-[80px]" />
      </body>
    </html>
  )
}
